# Generated by Django 3.2.6 on 2021-08-11 23:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('review_score', models.FloatField(null=True)),
            ],
        ),
    ]
