# Generated by Django 3.2.6 on 2021-08-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210815_1214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('client', 'product')},
        ),
    ]
