# Generated by Django 3.2.6 on 2021-08-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_wishlistitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='review_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
